specification-structure.md
The minimal example was incorrect as it had an implicit `null` value for `paths` which is not allowed. In YAML the only way to spell the empty object is with JSON syntax: `{}`
Signed-off-by: Mike Ralphson <mike.ralphson@gmail.com>
=> docs: fix missing {} on empty paths example

specification-components.md, specification-content.md, specification-parameters.md, specification-paths.md, specification-servers.md
On [https://oai.github.io/Documentation/specification-content.html](https://oai.github.io/Documentation/specification-content.html) (and others) two links in the `figcaption` are not being transformed, they still have their `.md` ending and lead the user to a 404 (compare to `previous page` link above it).
The embedded html doesn't transform the `a`'s `href`.
**Proposed change**
As links are not getting dynamically transformed, transform them manually:
`xyz.md` -> `xyz.html`
=> Fix 404 links in figcaption

specification-paths.md
Link to the OAS in this document follow the camelCase format (ex. https://spec.openapis.org/oas/v3.1.0#pathItemObject). Unfortunately, this link will only have the sidebar direct you to the content, while the docs themselves (right-content) will take you to your most recently navigated to spot on the page ([example](https://i.imgur.com/LsKNTvJ.png))
I suggest moving to kebab-case link which will actually take you to the content in the docs, rather than requiring a second click on the sidebar.
Ex. Try opening this in a new tab: [https://spec.openapis.org/oas/v3.1.0#path-item-object](https://spec.openapis.org/oas/v3.1.0#path-item-object). The sidebar won't point to the page unfortunately, but it isn't that hard to navigate and find your place
Macbook Pro, Google Chrome (latest). Command …
=> Updating OAS links to properly link to sections

start-here.md
https://github.com/OAI/Tooling - Switch over https://openapi.tools with the official repo
=> Update the OpenAPI Tooling link to point to the official OAI tooling repository

CONTRIBUTING.md, Gemfile, Gemfile.lock, _config.yml, best-practices.md, index.md, introduction.md, specification/components.md, specification/content.md, specification/docs.md, specification/index.md, specification/parameters.md, specification/paths.md, specification/servers.md, specification/structure.md
Closes #46 
The latest version of `just-the-docs` no longer seems to rewrite internal links from `.md` to `.html`.
=> Fix broken inline links 

Gemfile, Gemfile.lock, _config.yml
Deploys to Github pages were failing with "Warning: github-pages can't satisfy your Gemfile's dependencies" / "just-the-docs theme could not be found" with `theme` set in `_config.yml` so I had to set it back to `remote_theme`.
This change adds the `jekyll-remote-theme` gem to the local `Gemfile` so both local and deployed builds work the same.
The repo org for the `just-the-docs` theme has also changed, so this is updated too so we don't depend on a Github redirect.
=> fix: try to get remote theme working locally as well as deployed

_config.yml, best-practices.md, introduction.md
There were more links to openapi.tools which needed updating to tools.openapis.org as per #40
=> Fix additional references to openapi.tools

_includes/head_custom.html
Closes #41
This PR adds an OAI coloured 'Fork me on Github` banner top right using CSS from https://github.com/simonwhitaker/github-fork-ribbon-css - the aim is to prominently link to the documentation source and encourage contributions.
Tested locally and does not obscure the right hand hamburger menu when screen width is mobile-sized.
=> docs: add a fork me on Github banner, closes #41

specification/content.md, specification/parameters.md, specification/paths.md
The previous path was not relative to the root of the repository so it wasn't working, now it directs to the correct folder (examples) and file.
=> Fixed wrong path for the Tic Tac Toe sample API

specification/components.md, specification/docs.md, specification/parameters.md
I'm sorry if I opened another pull request, I didn't notice these other paths in other pages (parameters,components,docs).
=> Fixed other wrong paths for the Tic Tac Toe sample API

Gemfile, Gemfile.lock
This requirement popped up from followiong the CONTRIBUTING instructions.  The local server would not start without this package.
=> Jekyll now requires jekyll-include-cache

README.md, best-practices.md, index.md, introduction.md, specification/components.md, specification/content.md, specification/docs.md, specification/index.md, specification/parameters.md, specification/paths.md, specification/servers.md, specification/structure.md
The learn site previously decided to use OpenAPI Description, but hedged with terms like "OpenAPI Description document" and often reverted to "OpenAPI document" in the text.
A recent discussion on Slack finally revealed a consensus that
* Re-defining "document" away from its intuitive meaning as a single coherent thing (file or network resource) is confusing
* "description" has more support than "definition" or "document"
Following up on that discussion, this change standardizes on:
* "OpenAPI Description" as the term for the logical entity
* "OAD" as a standardized abbreviation, alongside OAS and OAI
* "document" to mean either local file or network resource (mostly avoiding "file", although I could go either way on that)
* "documentation" only refers to generated or hand-written docs …
=> Standardize on "Description" as discussed on Slack

specification/structure.md
"one or more text documents" doesn't rhyme with "commonly called <single filename>".
Move common filename down to "entry document".
=> structure.md: entry document called openapi.json

introduction.md
Fixes broken link mentioned in #70
=> fix: update broken link (fixes #70)

best-practices.md, glossary.md, specification/index.md
_This is an update of the "definitions" page from PR #69, which I will now close.  I renamed it "glossary" becuase that's what more people were using when we talked about it last.  The other material from the closed PR needs more rework before re-posting._
This adds definitions and acronym expansions for terms that users of and potential contributors to OpenAPI projects are likely to encounter.  It currently focuses on terms specific to OpenAPI, but could in the future also include some more standard terms to explain their usage in the OAS.
The `nav_order` changes ensure the glossary comes after the introduction but before everything else.  Although perhaps it should go after "Getting Started" but before "Introduction"?  Or maybe at the end?  I do not have strong feelings about this as …
=> Add a project glossary

.gitattributes
Correctly identifying main language of the repo on GitHub may help attracting more contributors.
|Before|After|
|---|---|
|![image](https://github.com/OAI/learn.openapis.org/assets/25753618/13bfc6f4-0f25-4cc4-a536-cf55b967cc12)|![image](https://github.com/OAI/learn.openapis.org/assets/25753618/6c60de6b-9be5-4d60-a8d7-ceb5bdf2ece2)|
|![image](https://github.com/OAI/learn.openapis.org/assets/25753618/99fd7908-c9bd-47c6-8607-72a4ad339b23)|![image](https://github.com/OAI/learn.openapis.org/assets/25753618/29a1a8ac-c67a-4b48-a9ce-64522721c852)|
=> Advertise Markdown files as "source code" of the repo

glossary.md
Replace "definintions" with "definitions".
=> Fix typo in glossary.md

.github/workflows/examples-tests.yaml, package-lock.json
The package-lock.json merged with #117 apparently was broken, this PR contains a working one.
The example-tests workflow will now also run on changes to its YAML file.
=> Fix example-tests workflow

Dockerfile, specification/servers.md
changes:
- minor modification in the Dockerfile to avoid a build warning
- added a link to the following page in specification/servers
=> The servers page was missing a link to the next page (security)

specification/content.md
Fix typo in "Content of Message bodies" page change "is" to "in"
=> Fix typo in content.md

community.md
When reviewing the Overlays documentation with the group this week, we realised that there's a disconnect between the information (outdated!) on the community site, and the place that we think most people would visit to find information (the documentation). This pull request brings over some of the information from the community repository readme, updates it, and makes it into a documentation page.
=> Add a community page to the documentation

specification/docs.md, specification/index.md
Fixes #129 after we talked about these two fields in a TDC meeting.
=> Add a clear overview of summary vs description

examples/index.md, overlay/index.md, referencing/index.md, specification/http-methods.md, specification/media-types.md, specification/parameters.md, specification/paths.md, specification/servers.md, specification/structure.md, specification/tags.md, upgrading/index.md, upgrading/v3.0-to-v3.1.md, upgrading/v3.1-to-v3.2.md
Rather than putting key information in the announcements, I've moved a lot of the content to here so that it can be linked to and evolved over time. Hopefully it's enough to get us started!
=> Prepare documentation additions for the 3.2 release
